/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Fd extends javax.swing.JFrame {

    /**
     * Creates new form Fd
     */
    public Fd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        am = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ag = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter principal amount :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter time in months :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Your Amount at Maturity :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Rs. ");

        t.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKeyTyped(evt);
            }
        });

        p.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        am.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        am.setText("Calculate Amount");
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("AGE : ");

        ag.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        ag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Name :");

        na.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });
        na.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                naKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Gender :");

        male.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(am))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(ag)
                                .addComponent(t, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(na))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(am))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>                        

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void pKeyTyped(java.awt.event.KeyEvent evt) {                           
         char c = evt.getKeyChar();
         if(Character.isLetter(c) && !evt.isAltDown()|| c=='\b')
         {
             evt.consume();
         }
            
    }                          

    private void pActionPerformed(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void tKeyTyped(java.awt.event.KeyEvent evt) {                           
        char c = evt.getKeyChar();
         if((Character.isDigit(c))|| c=='\b')
         {
             t.setEditable(true);
         }
         else
         {  JOptionPane.showMessageDialog(null,"Enter only integer");
             t.setText(null);
         
         }
    }                          

    private void amActionPerformed(java.awt.event.ActionEvent evt) {                                   
       //starting of code
        double p1 = Double.parseDouble(p.getText());
       int t1 = Integer.parseInt(t.getText());
       double r=0.0;
       double amo;
       if(p1>1000000) 
       {
           JOptionPane.showMessageDialog(null,"Enter principal amount less than 1000000 ");
       }
       else{
       if(t1>48)
       {
           JOptionPane.showMessageDialog(null,"Invalid Credential");
             p.setText(null);
        t.setText(null);
        ag.setText("");
        na.setText("");
        male.setSelected(false);
        female.setSelected(false);
       }
       else
       {
           if(male.isSelected())
           {
               if((Integer.parseInt(ag.getText()))>60)
               {
                 if(t1>0 && t1<=6)
                 {
                     r=6.20;
                 } 
                 else if(t1>6 && t1<=12)
                 {
                     r=6.25;
                 }
                 else if(t1>12 && t1<=18)
                 {
                     r=6.50;
                 }
                  else if(t1>18 && t1<=24)
                 {
                     r=6.75;
                 }
                  else if(t1>24 && t1<=30)
                 {
                     r=6.80;
                 }
                  else if(t1>30 && t1<=36)
                 {
                     r=6.85;
                 }
                  else if(t1>36 && t1<=48)
                 {
                     r=6.87;
                 }
                 
               }
               else
               {
                   if(t1>0 && t1<=6)
                 {
                     r=5.05;
                 } 
                 else if(t1>6 && t1<=12)
                 {
                     r= 5.10;
                 }
                 else if(t1>12 && t1<=18)
                 {
                     r=5.60;
                 }
                  else if(t1>18 && t1<=24)
                 {
                     r=5.75;
                 }
                  else if(t1>24 && t1<=30)
                 {
                     r=5.80;
                 }
                  else if(t1>30 && t1<=36)
                 {
                     r=5.85;
                 }
                  else if(t1>36 && t1<=48)
                 {
                     r=6.01;
                 }
               }
               }
           else
           {
               if((Integer.parseInt(ag.getText()))>58)
               {
                 if(t1>0 && t1<=6)
                 {
                     r=6.20;
                 } 
                 else if(t1>6 && t1<=12)
                 {
                     r=6.25;
                 }
                 else if(t1>12 && t1<=18)
                 {
                     r=6.50;
                 }
                  else if(t1>18 && t1<=24)
                 {
                     r=6.75;
                 }
                  else if(t1>24 && t1<=30)
                 {
                     r=6.80;
                 }
                  else if(t1>30 && t1<=36)
                 {
                     r=6.85;
                 }
                  else if(t1>36 && t1<=48)
                 {
                     r=6.87;
                 }
                 
               }
               else
               {
                   if(t1>0 && t1<=6)
                 {
                     r=5.05;
                 } 
                 else if(t1>6 && t1<=12)
                 {
                     r= 5.10;
                 }
                 else if(t1>12 && t1<=18)
                 {
                     r=5.60;
                 }
                  else if(t1>18 && t1<=24)
                 {
                     r=5.75;
                 }
                  else if(t1>24 && t1<=30)
                 {
                     r=5.80;
                 }
                  else if(t1>30 && t1<=36)
                 {
                     r=5.85;
                 }
                  else if(t1>36 && t1<=48)
                 {
                     r=6.01;
                 }} 
           }
                      
           } 
       
     int t2= ((t1)/3);
     int t3= (t1-t2*3);
     
     double am1 = p1*Math.pow((1+((r/4)/100)),t2);
     if(t3>0)
     {
          amo = am1*Math.pow((1+((r/12)/100)),t3);
     }
       else
     {
         amo=am1;
     }
    am.setText("Rs "+amo+"");}
    }                                  
//end of code
    private void agActionPerformed(java.awt.event.ActionEvent evt) {                                   
       
    }                                  

    private void agKeyTyped(java.awt.event.KeyEvent evt) {                            
       char c = evt.getKeyChar();
         if((Character.isDigit(c))|| c=='\b')
         {
             ag.setEditable(true);
         }
         else
         {  JOptionPane.showMessageDialog(null,"Enter only integer");
             ag.setText(null);
         
         }
    }                           

    private void naActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void naKeyTyped(java.awt.event.KeyEvent evt) {                            
         char c = evt.getKeyChar();
         if(Character.isLetter(c)|| Character.isWhitespace(c) || Character.isISOControl(c))
         {
             na.setEditable(true);
         }
         else
         {
             na.setEditable(false);
         }
         
    }                           

    private void agKeyPressed(java.awt.event.KeyEvent evt) {                              
        // TODO add your handling code here:
    }                             

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {                                     
       if(male.isSelected())
       {
           female.setSelected(false);
       }
    }                                    

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {                                       
       if(female.isSelected())
       {
           male.setSelected(false);
       }
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         male.setSelected(false);
         female.setSelected(false);
         na.setText("");
         ag.setText("");
         p.setText("");
         t.setText("");
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField ag;
    private javax.swing.JButton am;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField na;
    private javax.swing.JTextField p;
    private javax.swing.JTextField t;
    // End of variables declaration                   
}
